### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics|Memcached

#This will create it in specific Tier. Replace <TIER_NAME>
#metricPrefix: Server|Component:<TIER_NAME>|Custom Metrics|Memcached

# List of Memcached Servers
servers:
  - server: "localhost:11211"
    displayName: localhost


#timeout in ms to get data for all the servers
timeout: 60000


# The performance metrics exposed by Memcached stats command are mainly counters. If reported as is, they just represent
# an ever-increasing value. To make these metrics more useful delta from the previous run is calculated and reported as the
# default behavior. List the metrics in "ignoreDelta", if delta calculation should be avoided for any metric.
ignoreDelta: [

]

# Jeremy Davis removing the below as it is no longer inherent feature
#Metric Overrides. Change this if you want to transform the metric key or want more control on the metrics.
# For most cases, this should not be touched.
#
#----------------------------------------------------------------------------------------------------------------------
#metricOverrides:
#  - metricKey: ".*version.*"
#    disabled: true
#
#  - metricKey: ".*libevent.*"
#    disabled: true
#
#  - metricKey: ".*time"
#    disabled: true

